<script lang="ts">
  import { resolve } from '$app/paths';
  import type { IContestReport } from '$lib/server/report_types';
  import Report from '$lib/components/Report.svelte';

  interface Props {
    data: import('./$types').PageData;
  }

  // Avoid capturing the initial `data` value only; derive from props for client-side navigation.
  let props: Props = $props();
  let report: IContestReport = $derived.by(() => props.data.report);
  let path: string = $derived.by(() => props.data.path);

  // Construct image path: images/{path}/{office}.png
  // The path param includes both path and office, so we need to extract office
  let imagePath = $derived.by(() => {
    const pathParts = path.split('/');
    const office = pathParts[pathParts.length - 1];
    const basePath = pathParts.slice(0, -1).join('/');
    return `https://approval.vote/images/${basePath}/${office}.png`;
  });
</script>

<svelte:head>
  <title
    >approval.vote: {report.info.jurisdictionName} / {report.info.officeName} / {report.info.date.slice(
      0,
      4
    )}</title
  >

  <!-- X (Twitter) Card Tags -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@felixsargent" />
  <meta name="twitter:creator" content="@felixsargent" />
  <meta name="twitter:title" content="Approval Voting Results: {report.info.jurisdictionName} {report.info.officeName} ({report.info.date.slice(0, 4)})" />
  <meta
    name="twitter:description"
    content="Detailed approval voting election results and analysis for {report.info.jurisdictionName} {report.info.officeName} - {report.info.electionName} held in {report.info.date.slice(0, 4)}. View candidate vote counts, co-approval patterns, and voting distributions."
  />
  <meta name="twitter:image" content={imagePath} />
  <meta name="twitter:image:width" content="1200" />
  <meta name="twitter:image:height" content="630" />
  <meta
    name="twitter:image:alt"
    content="Election results visualization showing approval voting outcomes for {report.info.jurisdictionName} {report.info.officeName}"
  />

  <!-- Open Graph Tags (also used by X) -->
  <meta property="og:type" content="article" />
  <meta property="og:url" content="https://approval.vote/report/{path}" />
  <meta property="og:title" content="Approval Voting Results: {report.info.jurisdictionName} {report.info.officeName} ({report.info.date.slice(0, 4)})" />
  <meta
    property="og:description"
    content="Detailed approval voting election results and analysis for {report.info.jurisdictionName} {report.info.officeName} - {report.info.electionName} held in {report.info.date.slice(0, 4)}. View candidate vote counts, co-approval patterns, and voting distributions."
  />
  <meta property="og:image" content={imagePath} />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:type" content="image/png" />
  <meta property="og:logo" content="https://approval.vote/icons/icon-512x512.png" />
</svelte:head>

<div class="wide container">
  <Report {report} />
  <hr />
  <div class="row">
    <p style="font-style: italic;">
      This report was generated by <a href="{resolve('/', {})}">approval.vote</a>
      and may be reproduced under
      <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>. Learn more
      <a href="{resolve('/about', {})}">about approval.vote</a>.
      <span style="margin-left: 1em;">
        <a href={imagePath.replace('https://approval.vote', '')}>View card image →</a>
      </span>
    </p>
  </div>
</div>

<a style="display:none;" href={resolve(`/card/${path}`, {})}>card</a>
